Atualizar o Plus

diff --git a/Modulos/64/Plus b/Modulos/64/Plus
--- a/Modulos/64/Plus
+++ b/Modulos/64/Plus
@@ -25,18 +25,18 @@ fun_bar() {
         touch $HOME/fim
     ) >/dev/null 2>&1 &
     tput civis
-    echo -ne "\033[1;31m❪\033[1;33mAGUARDE \033[1;37m> \033[1;32m|"
+    echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
     while true; do
         for ((i = 0; i < 18; i++)); do
-            echo -ne "\033[1;32m█"
+            echo -ne "\033[1;31m#"
             sleep 0.1s
         done
         [[ -e $HOME/fim ]] && rm $HOME/fim && break
-        echo -e "\033[1;32m|"
+        echo -e "\033[1;33m]"
         sleep 1s
         tput cuu1
         tput dl1
-        echo -ne "\033[1;31m❪\033[1;33mAGUARDE \033[1;37m> \033[1;32m|"
+        echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
     done
     echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
     tput cnorm
@@ -45,6 +45,17 @@ function verif_key() {
     krm=$(echo '5:q-3gs2.o7%8:1' | rev)
     chmod +x $_Ink/list >/dev/null 2>&1
     [[ ! -e "$_Ink/list" ]] && {
+        echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
+        rm -rf $HOME/Plus >/dev/null 2>&1
+        sleep 2
+        clear
+        exit 1
+    }
+}
+function verif_key2() {
+    krm=$(echo '5:q-3gs2.o7%8:1' | rev)
+    chmod +x $_Ink/listARM >/dev/null 2>&1
+    [[ ! -e "$_Ink/listARM" ]] && {
         echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
         rm -rf $HOME/Plus >/dev/null 2>&1
         sleep 2
@@ -89,12 +100,28 @@ echo -e "\033[1;33m  UMA MELHOR EXPERIÊNCIA E VISUALIZACAO DO MESMO!\033[0m"
 echo ""
 echo -e "\033[1;31m═══════════[\033[1;33m • \033[1;32mBy: :@alfalemos\033[1;33m •\033[1;31m ]═══════════\033[0m"
 echo ""
-echo -e "\n\033[1;36mVERIFICANDO LINK... \033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/alfainternet/SSHPLUS/master/Modulos/list >/dev/null 2>&1
+#-----------------------------------------------------------------------------------------------------------------
+echo -ne "\033[1;36mGENERAR AS KEY FREE [N/S]: \033[1;37m"
+read x
+[[ $x = @(n|N) ]] && exit
+echo -e "\033[1;36mSelecione a Arquitetura da sua VPS: \033[1;37m"
+echo -e "[1] - x86_64"
+echo -e "[2] - aarch64(ARM)"
+echo -ne "\033[1;36mOpção: \033[1;37m"
+read resposta
+if [[ "$resposta" = '1' ]]; then
+    sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config >/dev/null 2>&1
+    service ssh restart >/dev/null 2>&1
+    mkdir /etc/rec >/dev/null 2>&1
+    echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m 16983:16085\033[0m"
+    rm $_Ink/list >/dev/null 2>&1
+    wget -P $_Ink https://raw.githubusercontent.com/alfainternet/SSHPLUS/master/Modulos/list >/dev/null 2>&1
     verif_key
     sleep 3s
     echo "/bin/menu" >/bin/h && chmod +x /bin/h >/dev/null 2>&1
     rm versao* >/dev/null 2>&1
     wget https://raw.githubusercontent.com/alfainternet/SSHPLUS/master/Modulos/versao >/dev/null 2>&1
+    >/dev/null 2>&1
     rm v2raymanager >/dev/null 2>&1
     wget https://raw.githubusercontent.com/alfainternet/SSHPLUS/master/Modulos/v2raymanager >/dev/null 2>&1
     wget https://raw.githubusercontent.com/alfainternet/SSHPLUS/master/Modulos/botteste.sh >/dev/null 2>&1
@@ -105,19 +132,9 @@ echo -e "\n\033[1;36mVERIFICANDO LINK... \033[0m" ; rm $_Ink/list > /dev/null 2>
     wget https://raw.githubusercontent.com/alfainternet/SSHPLUS/master/Modulos/ShellBot.sh >/dev/null 2>&1
     chmod 777 ShellBot.sh >/dev/null 2>&1
     cd >/dev/null 2>&1
-    chmod 777 licence >/dev/null 2>&1
-    mkdir /etc/rec >/dev/null 2>&1
-    cd /etc/rec
-    wget https://raw.githubusercontent.com/alfainternet/SSHPLUS/master/Modulos/licence >/dev/null 2>&1
-    chmod 777 licence >/dev/null 2>&1
-    cd >/dev/null 2>&1
     #-----------------------------------------------------------------------------------------------------------------
     echo -e "\n\033[1;32mKEY VALIDA!\033[1;32m"
     sleep 1s
-    echo ""
-    [[ -f "$HOME/usuarios.db" ]] && {
-        clear
-        figlet "SSH-PLUS" | lolcat
     echo ""
     [[ -f "$HOME/usuarios.db" ]] && {
         clear
@@ -144,16 +161,12 @@ echo -e "\n\033[1;36mVERIFICANDO LINK... \033[0m" ; rm $_Ink/list > /dev/null 2>
     clear
     tput setaf 7
     tput setab 4
-    tput bold 
-    figlet "SSH-PLUS" | lolcat
+    tput bold
     printf '%35s%s%-18s\n' " AGUARDE A INSTALAÇÃO"
     tput sgr0
     echo ""
-    figlet "SSH-PLUS" | lolcat
     echo ""
     echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mATUALIZANDO SISTEMA \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
-    echo ""
-    figlet "SSH-PLUS" | lolcat 
     echo ""
     echo -e "    \033[1;33mATUALIZAÇÕES COSTUMA DEMORAR UM POUCO!\033[0m"
     echo ""
@@ -165,11 +178,7 @@ echo -e "\n\033[1;36mVERIFICANDO LINK... \033[0m" ; rm $_Ink/list > /dev/null 2>
     fun_bar 'fun_attlist'
     clear
     echo ""
-    figlet "SSH-PLUS" | lolcat 
-    echo ""
     echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALANDO PACOTES \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
-    echo ""
-    figlet "SSH-PLUS" | lolcat 
     echo ""
     echo -e "\033[1;33mALGUNS PACOTES SAO EXTREMAMENTE  NECESSÁRIOS !\033[0m"
     echo ""
@@ -188,26 +197,124 @@ echo -e "\n\033[1;36mVERIFICANDO LINK... \033[0m" ; rm $_Ink/list > /dev/null 2>
     ufw allow 8080/tcp
     clear
     echo ""
-    figlet "SSH-PLUS" | lolcat 
-    echo ""
     echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
-    echo ""
-    figlet "SSH-PLUS" | lolcat 
     echo ""
     echo -e "      \033[1;33mOTIMIZANDO PYTHON \033[0m"
     echo ""
     fun_bar 'otimize_python'
     clear
     echo ""
-    figlet "SSH-PLUS" | lolcat 
-    echo ""
     echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
-    echo ""
-    figlet "SSH-PLUS" | lolcat 
     echo ""
     echo -e "      \033[1;33mCONCLUINDO FUNÇÕES E DEFINIÇÕES! \033[0m"
     echo ""
     fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
+    clear
+    echo ""
+    cd $HOME
+    echo -e "        \033[1;33m • \033[1;32mINSTALACAO CONCLUIDA\033[1;33m • \033[0m"
+    echo ""
+    echo -e "\033[1;31m \033[1;33mCOMANDO PRINCIPAL: \033[1;32mmenu\033[0m"
+    echo -e "\033[1;33m MAIS INFORMACOES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@alfalemos\033[0m"
+    rm $HOME/Plus && cat /dev/null >~/.bash_history && history -c
+elif [[ "$resposta" = '2' ]]; then
+    sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config >/dev/null 2>&1
+    service ssh restart >/dev/null 2>&1
+    echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m 16983:16085\033[0m"
+    rm $_Ink/listARM >/dev/null 2>&1
+    wget -P $_Ink https://www.dropbox.com/s/cs5poyigwm97dyd/listARM >/dev/null 2>&1
+    verif_key2
+    sleep 3s
+    echo "/bin/menu" >/bin/h && chmod +x /bin/h >/dev/null 2>&1
+    rm versao* >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/alfainternet/SSHPLUS/master/Modulos/versao >/dev/null 2>&1
+    rm v2raymanager >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/alfainternet/SSHPLUS/master/Modulos/v2raymanager >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/alfainternet/SSHPLUS/master/Modulos/botteste.sh >/dev/null 2>&1
+    chmod 777 v2raymanager >/dev/null 2>&1
+    chmod 777 botteste.sh >/dev/null 2>&1
+    mkdir $HOME/BOT >/dev/null 2>&1
+    cd $HOME/BOT
+    wget https://raw.githubusercontent.com/alfainternet/SSHPLUS/master/Modulos/ShellBot.sh >/dev/null 2>&1
+    chmod 777 ShellBot.sh >/dev/null 2>&1
+    cd >/dev/null 2>&1
+    #-----------------------------------------------------------------------------------------------------------------
+    echo -e "\n\033[1;32mKEY VALIDA!\033[1;32m"
+    sleep 1s
+    echo ""
+    [[ -f "$HOME/usuarios.db" ]] && {
+        clear
+        echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
+        echo ""
+        echo -e "                 \033[1;33m• \033[1;31mATENCAO \033[1;33m• \033[0m"
+        echo ""
+        echo -e "\033[1;33mUma base de Dados de Usuários \033[1;32m(usuarios.db) \033[1;33mFoi"
+        echo -e "Encontrada! Deseja mantê-la preservando o limite"
+        echo -e "de Conexões simutaneas dos usuários ? Ou Deseja"
+        echo -e "criar uma nova base de dados ?\033[0m"
+        echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mManter Base de Dados Atual\033[0m"
+        echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCriar uma Nova Base de Dados\033[0m"
+        echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
+        echo ""
+        tput setaf 2
+        tput bold
+        read -p "Opção ?: " -e -i 1 optiondb
+        tput sgr0
+    } || {
+        awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' >$HOME/usuarios.db
+    }
+    [[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' >$HOME/usuarios.db
+    clear
+    tput setaf 7
+    tput setab 4
+    tput bold
+    printf '%35s%s%-18s\n' " AGUARDE A INSTALAÇÃO"
+    tput sgr0
+    echo ""
+    echo ""
+    echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mATUALIZANDO SISTEMA \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
+    echo ""
+    echo -e "    \033[1;33mATUALIZAÇÕES COSTUMA DEMORAR UM POUCO!\033[0m"
+    echo ""
+    fun_attlist() {
+        apt-get update -y
+        [[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
+        echo "crz: $(date)" >/usr/share/.plus/.plus
+    }
+    fun_bar 'fun_attlist'
+    clear
+    echo ""
+    echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALANDO PACOTES \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+    echo ""
+    echo -e "\033[1;33mALGUNS PACOTES SAO EXTREMAMENTE  NECESSÁRIOS !\033[0m"
+    echo ""
+    inst_pct() {
+        _pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip" "python" "at")
+        for _prog in ${_pacotes[@]}; do
+            apt install $_prog -y
+        done
+        pip install speedtest-cli
+    }
+    fun_bar 'inst_pct'
+    [[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp
+    ufw allow 80/tcp
+    ufw allow 3128/tcp
+    ufw allow 8799/tcp
+    ufw allow 8080/tcp
+    clear
+    echo ""
+    echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+    echo ""
+    echo -e "      \033[1;33mOTIMIZANDO PYTHON \033[0m"
+    echo ""
+    fun_bar 'otimize_python'
+    clear
+    echo ""
+    echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+    echo ""
+    echo -e "      \033[1;33mCONCLUINDO FUNÇÕES E DEFINIÇÕES! \033[0m"
+    echo ""
+    fun_bar "$_Ink/listARM $_lnk $_Ink $_1nk $key"
     clear
     echo ""
     cd $HOME
@@ -232,3 +339,11 @@ echo -e "\n\033[1;36mVERIFICANDO LINK... \033[0m" ; rm $_Ink/list > /dev/null 2>
     echo -e "\033[01;31m║\033[1;33mPARA INICIAR DIGITE: \033[1;32mmenu\033[0m"
     echo -e "\033[01;31m║\033[1;33m MAIS INFORMACOES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@alfalemos\033[0m"
     rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
+
+else
+
+    echo ""
+    echo -e "\033[1;31mOpcao invalida !\033[0m"
+    sleep 1
+    exit
+fi
